services:
  asciimage:
    build:
      context: server/
    ports:
      - "3000:3000"
      
  asciimage-web:
    build:
      context: client/asciimage-client
    ports:
      - "5000:80"
    depends_on:
      - asciimage
    links:
      - asciimage